language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
  - export DJANGO_SETTINGS_MODULE=timezone_field.test_settings
install:
  - pip install -e .
script:
  - django-admin.py test timezone_field
