language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4.3 DB=postgres
  - DJANGO=1.4.3 DB=sqlite
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install psycopg2
  - pip install django==$DJANGO
  - pip install pep8
  - pip install -e .
before_script:
  - export DJANGO_SETTINGS_MODULE=timezone_field.test_settings
  - psql -c 'create database timezone_field_test;' -U postgres
  - pep8 .
script:
  - django-admin.py test timezone_field
