language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO='django>=1.4,<1.5' DB='postgres'
  - DJANGO='django>=1.4,<1.5' DB='sqlite'
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install psycopg2
  - pip install $DJANGO
  - pip install flake8
  - pip install -e .
before_script:
  - export DJANGO_SETTINGS_MODULE=timezone_field.test_settings
  - psql -c 'create database timezone_field_test;' -U postgres
  - flake8 .
script:
  - django-admin.py test timezone_field
