language: python
install:
  - pip install tox coveralls
before_script:
  - psql -c 'create database timezone_field_tests;' -U postgres
script:
  - tox
  - tox -e coverage
after_success:
  - coveralls
